version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.12
    resource_class: small
    steps:
      - checkout
      - run: pip install jsonschema
      - run: jsonschema -i nests.json nests.schema.json
